spring:
  datasource:
    #url: jdbc:h2:file:./rss.db;DATABASE_TO_UPPER=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;INIT=CREATE SCHEMA IF NOT EXISTS rss
    url: jdbc:h2:mem:rss;DATABASE_TO_UPPER=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;INIT=CREATE SCHEMA IF NOT EXISTS rss
    username: dev
    password: password
    hikari:
      schema: rss
  flyway:
    locations: classpath:db/migration
    schemas: rss

